### ISSUE TITLE
[Feature Request] Gradle support

### ISSUE THREAD

**Issue by ardittristan** [bsorrentino/java2typescript#18]
Would it be possible to add Gradle support? Or if it's a lot of work could you maybe give some pointers so i can take a look at porting?

Thanks!

**Comment by bsorrentino** [comment]
HI @ardittristan 

I don't think that it will be complex ....  let me assess effort and if it is reasonable I'll provide also gradle support

**Comment by bsorrentino** [comment]
Hi @ardittristan 

the only thing that you've to do is configure the `annotation processor` in your gradle build

**Comment by ardittristan** [comment]
Does that also enforce rhino compatibility or does that need to be set elsewhere?

**Comment by bsorrentino** [comment]
Rhino compatibility enforcing is just a matter of `annotation processor` configuration . Take a look to `options.compatibility` parameter

**Comment by ardittristan** [comment]
I can't seem to get options.compatibility to work anywhere in my build.gradle (sorry if I'm asking stupid questions)

**Comment by ardittristan** [comment]
oh, and I also noticed that the archetype and parent packages are missing 1.2.0 on the maven central repository

**Comment by bsorrentino** [comment]
Hi @ardittristan could you share your gradle configuration?

about archetype I’ll fix it as soon as possible

**Comment by ardittristan** [comment]
https://gist.github.com/ardittristan/bce1c046cb08bf2090e5229f78c732a0#file-build-gradle-L338
until line 343 is the added config (coming from Anuken/Mindustry )

adding the package to classpath didn't help either.

**Comment by ardittristan** [comment]
(my end goal is basically generating typescript declarations from upstream)

**Comment by bsorrentino** [comment]
Hi @ardittristan 

I've find out how to apply rhino compatibility options on annotation processor using gradle (ref. [here](https://dagger.dev/hilt/gradle-setup.html))

```kotlin
javaCompileOptions {
  annotationProcessorOptions {
    arguments += ["compatibility" : "rhino"]
  }
}
```

**Comment by ardittristan** [comment]
That way of setting it up only works on android-gradle, I did figure out how to do it the correct way though in normal gradle.

```groovy
compileJava {
    options.compilerArgs += '-Acompatibility=rhino'
}
```
